name: Deploy to FTP Server

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the version of Node.js that your project requires

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # This will run `tsc -b && vite build`

      - name: Upload to FTP server
        uses: sebastianpopp/ftp-action@v1.1.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'dist'  # The directory where Vite outputs the build (adjust if different)
          remoteDir: /web
